### ISSUE TITLE
Stuck at "Calculating delay between hosts"

### ISSUE THREAD

**Issue by nemobis** [jwbensley/Etherate#21]
Whatever command I try from the [examples](https://null.53bits.co.uk/index.php?page=etherate-use-cases), it gets stuck forever (well, at least several minutes) at "Calculating delay between hosts".

This is likely because my network blocks (all?) ICMP. Even if it's considered obvious, it would be nice to specify in the README (or maybe to give up after a while?).

```
$ sudo etherate -f 1500
Running in TX mode
Using device eth0 with address 64:00:6a:6c:5e:f5, interface index 2
Entering promiscuous mode
Source MAC 00:00:5e:00:00:01
Destination MAC 00:00:5e:00:00:02
Sending gratuitous broadcasts...
Done.

Synchronising settings with RX host
Settings have been synchronised

Frame size if 1514 bytes
Calculating delay between hosts...
q^CLeaving promiscuous mode
```

See firewalls:
```
$ sudo lft -E ripe.net

Tracing _______________________.

TTL  LFT trace to www.ripe.net (193.0.6.139):80/tcp
 1   10.169.0.252 10.8/17.6ms
**   [firewall] the next gateway may statefully inspect packets
 2   10.169.174.177 5.3/15.9ms
**   [neglected] no reply packets received from TTLs 3 through 4
**   [4.2-3 BSD bug] the next gateway may errantly reply with reused TTLs
 5   * [target] www.ripe.net (193.0.6.139):80 18.4ms
```

I'm on:
```
$ uname -a
Linux fondazione-Precision-Tower-3620 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks for the patience and feel free to close as invalid. :-)

**Comment by jwbensley** [comment]
Hi @nemobis, thanks for the report.

Etherate works directly over layer 2 Ethernet, there is no ICMP (or IP for that matter). The Rx and Tx hosts need to be on the same broadcast domain as one can only specify source and destiantion MAC addresses not IPs.

Please confirm if your Tx and Rx hosts are on the same layer 2 Ethernet broadcast domain as each other and if you are using the latest version of Etherate on both hosts.

**Comment by nemobis** [comment]
I had no idea I had to run the program on two hosts at the same time, it seems I misunderstood everything (I still find no clue about this in README, INSTALL nor the other pages they link).

**Comment by jwbensley** [comment]
@nemobis understood, it's obvious to me as I wrote Etherate so I see where you coming from. I have added a "Usage" section [here](https://null.53bits.co.uk/index.php?page=etherate) and have mentioned this in the Readme which will be update in my next push to Github. Thanks for the feedback.

**Comment by nemobis** [comment]
Thanks! That looks good to this n00b. :)
