### ISSUE TITLE
Test not starting

### ISSUE THREAD

**Issue by jwbensley** [jwbensley/Etherate#22]
Sent in via email:

> I have tried some sample tests using etherate.
> 
> I have used below commands in that order
> 
> Test 1
> 
> In Rx
> sudo etherate –r
> 
> In Tx
> sudo etherate
> 
> I can able to see the speed, number of  frames transmitted at Tx side but in Rx side I don’t see the frames received or its speed. It prints the “settings have been synchronized” some calculated delay values  and the title row of result “ Seconds MbpsRx MBsRx FrmRx/s FramesRx” but no values below this row.
> 
> What could be the issue?

**Comment by jwbensley** [comment]
Sent response via email requesting more info;

> Sorry for the delay in my response I have been away. I have opened an issue on the GitHub page here (https://github.com/jwbensley/Etherate/issues/22) in case you are experiencing a bug we can track it's progress there.
> 
> Please can you tell me a little bit about how you are running Etherate;
> 
> Are you running Etherate between two machines on the same LAN, or two Virtual Machines on the same bridge adapter?
> 
> When you run Etherate it says something like:
> 
> "Using device enp0s25 with address 3c:97:0e:bd:62:82, interface index 2"
> 
> What interface is Etherate using on each device?
> 
> Are both those interfaces up and running?
> 
> Are they in the same broadcast domain?

**Comment by sudhanthiradasan** [comment]
Hi James,
I have attached the screenshot taken at both Tx and Rx. I'm running etherate between two machines on the same network. 

Actually at Rx side it waits in a while loop indefinitely for the first test frame to be received. That’s why I don’t see any progress, after that in Rx side.

When I manually changed the FIRST_FRAME value to true, it works in Rx side.

I don’t know why the first test frame is lost at the Rx side. Even though I first run Rx and then run Tx.  
![etheraterx](https://user-images.githubusercontent.com/28643926/27781781-2e2652dc-5fed-11e7-85e6-131a1fd73457.jpg)
![etheratetx](https://user-images.githubusercontent.com/28643926/27781780-2e1dbab4-5fed-11e7-8fd7-d869e1a512f4.png)

**Comment by jwbensley** [comment]
@sudhanthiradasan Thanks for the info, when you change `FIRST_FRAME` to `true` and you say that it works, does the Rx side start to could up the same amount of data that Tx is sending, or does the duration increment Rx but it says it's recieving 0Mbps or traffic?

Many thanks.

**Comment by jwbensley** [comment]
Please can you also grab the latest version of Etherate as I have updated it with some bug fixes since you have initially reported this issue.

**Comment by sudhanthiradasan** [comment]
Even in the latest version I'm seeing the same issue

**Comment by jwbensley** [comment]
@sudhanthiradasan Thanks for your response. Can you please share the output of the following command from both machines:

```
lspci
sudo etherate -l
ip l
```

If you can provide this output I will try and make a patch over the coming weekend for you to test.

**Comment by sudhanthiradasan** [comment]
![m1](https://user-images.githubusercontent.com/28643926/28516113-b1ec1da4-707d-11e7-91e6-c0288d69207c.PNG)
[m1_lspci.txt](https://github.com/jwbensley/Etherate/files/1169305/m1_lspci.txt)
![m2](https://user-images.githubusercontent.com/28643926/28516114-b1ee713a-707d-11e7-936f-e9c0f55506f3.PNG)
[m2_lspci.txt](https://github.com/jwbensley/Etherate/files/1169306/m2_lspci.txt)

Hi, 
Attached the results from both the machines m1 and m2.

**Comment by jwbensley** [comment]
@sudhanthiradasan I am sorry for the MASSIVE delay! I have been very busy with my day job recently. This should now be fixed in the newest version. Are you still able to check?

I wasn't able to replicate the issue for a while and today a friend of mine experienced the same issue. I found a way to replicate the issue and fix it. Please let me know if this is fixed for you now.

**Comment by sudhanthiradasan** [comment]
Thanks jwbensley.. Its working fine with the current version

**Comment by jwbensley** [comment]
Thanks @sudhanthiradasan for taking the time to test this again!

**Comment by jwbensley** [comment]
Fixed in the commit to v 1.14 moving from beta to production ready:
https://github.com/jwbensley/Etherate/commit/d67ffec29bf20d582abc8a4b7cd81b8d2e281759
