### ISSUE TITLE
Any chance for adding this to Homebrew for Mac Users?

### ISSUE THREAD

**Issue by wmclendon** [jwbensley/Etherate#4]
not an issue per se, but not sure how else to communicate the request.  Assuming this tool would run on Mac (don't see why not), any chance you could add it to Homebrew for easy install for Mac Users?

**Comment by jwbensley** [comment]
@wmclendon Thanks for the idea. I will look into it and get back to you!

**Comment by jwbensley** [comment]
@wmclendon I have looked into this.

So "yes" it is achievable in terms of adding Etherate to the Homebrew repo, however;

- I don't have a Mac nor access to one so I can't test Etherate on Mac to see if it even works
- If it doesn’t work but only needs minor changes to make it work, I can’t address those minor issues

So for those reasons I don’t want submit Etherate to Homebrew. Someone (anyone!) with a Mac can do this for me, I don’t mind, but I can’t honestly make that request to Homebrew without having a Mac to test on, that wouldn’t be right.

I will close this request unless you have any further input?

**Comment by jwbensley** [comment]
If someone wants to pay for 1 month of "Mac time" I'm happy to give it a go, with no promises that it will work:

https://www.macincloud.com/pricing/compare

**Comment by jwbensley** [comment]
I've got a copy of Yosemite now so I'll evaluate what is the "gap" to get Etherate running on OS X.

**Comment by gordlea** [comment]
I tried compiling on macOS sierra, and got the following:

```
➜  Etherate git:(master) ✗ make
g++ -DPACKAGE_NAME=\"etherate\" -DPACKAGE_TARNAME=\"etherate\" -DPACKAGE_VERSION=\"0.10.0\" -DPACKAGE_STRING=\"etherate\ 0.10.0\" -DPACKAGE_BUGREPORT=\"jwbensley@gmail.com\" -DPACKAGE_URL=\"https://null.53bits.co.uk/index.php\?page=etherate\" -DPACKAGE=\"etherate\" -DVERSION=\"0.10.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.     -Wall -ftrapv -lrt -D _GNU_SOURCE -DPACKAGE=\"etherate\" -DSYSCONFDIR=\"/usr/local/etc\" -DLOCALSTATEDIR=\"/usr/local/var\" -DLIBEXECDIR=\"/usr/local/libexec\" -DLIBDIR=\"/usr/local/lib\" -DPACKAGE_VERSION=\"0.10.0\" -O3 -g -pipe -MT etherate.o -MD -MP -MF .deps/etherate.Tpo -c -o etherate.o etherate.cpp
clang: warning: -lrt: 'linker' input unused
etherate.cpp:39:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>        // __bswap_64
         ^
1 error generated.
make: *** [etherate.o] Error 1
➜  Etherate git:(master) ✗
```

Also see (https://github.com/shirok/Gauche/pull/218/commits/469873cfe4420dc06a2fc2e7fc07a42bf096a2ff) for an example of getting libtoolize going on OS X.

**Comment by jwbensley** [comment]
I have no access to a MAC so I can't try to fix this. I only support Linux. If someone else whats to add in MAC support they can and make a pull request. Closing this issue now.
